trigger: none
pr: none

jobs:
- job: publish_sku
  pool:
    name: $(BUILD_POOL)
  steps:
  - script: |
    docker run --rm \
    -v ${PWD}:/go/src/github.com/Azure/aks-engine \
    -w /go/src/github.com/Azure/aks-engine \
    -e SKU_PREFIX=${SKU_PREFIX} \
    -e SKU_TEMPLATE_FILE=${SKU_TEMPLATE_FILE} \
    -e PUBLISHER=${PUBLISHER} \
    -e OFFER=${OFFER} \
    ${DEIS_GO_DEV_IMAGE} ./vhd/publishing/new-windows-sku.sh
  - task: PublishPipelineArtifact@1
    inputs:
      artifact: 'sku_info'
      path: 'sku-publishing-info.json'

